FROM 2dii/r-packages:latest
LABEL maintainer='Mauro Lepore'

COPY PACTA_analysis /bound
COPY create_interactive_report /create_interactive_report
COPY pacta-data /pacta-data
COPY StressTestingModelDev /StressTestingModelDev

RUN exit 0
