FROM 2dii/r-packages:latest
LABEL maintainer='Mauro Lepore'

COPY PACTA_analysis /pacta/PACTA_analysis
COPY create_interactive_report /pacta/create_interactive_report
COPY pacta-data /pacta/pacta-data
COPY StressTestingModelDev /pacta/StressTestingModelDev

RUN exit 0
