#! /bin/bash

tag="$1"
shift
repos="$@"

for repo in ${repos}
do
    origin="$(git -C ${repo} remote get-url origin)"
    read -p "Are you sure you want to push $tag to ${origin} (y/n)? " -n 1 -r
    echo    # move to a new line

    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        git -C "${repo}" push origin "${tag}"
    fi
done

exit 0
